name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie 
    steps:
      - name: Log node version
        run: node -v
      - name: Steps with Docker
        uses: docker://node:12.14.1-alpine3.10
        with: 
          entrypoint: /bin/echo
          args: Hello Woorld! 
      - name: Log Node Version as an ENTRYPOOINT
        uses: docker://node:12.14.1-alpine3.10
        with: 
          entrypoint: /usr/local/bin/node
          args: -v
  node-docker:
    runs-on: ubuntu-latest
    #container: 
    #  image: node:13.5.0-alpine3.10 
    services:
      app:
        image: alialaa17/node-api
        ports: 
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Post a user to the DB
        run: "curl -X POST http://localhost:3001/api/user -H 'content-Type: application/json' -d ' {\"username\": \"hello\", \"address\": \"addressDetails\" }'"
      - name: Get All users
        run: curl http://localhost:3001/api/users 
      