name: Container
on: [push]
#branches:
#  - master
#  - feature

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie 
    steps:
      - name: Log node version
        run: node -v
      - name: Steps with Docker
        uses: docker://node:12.14.1-alpine3.10
        with: 
          entrypoint: /bin/echo
          args: Hello World! 
      - name: Log Node Version as an ENTRYPOOINT
        uses: docker://node:12.14.1-alpine3.10
        with: 
          entrypoint: /usr/local/bin/node
          args: -v
      - uses: actions/checkout@v1
      - name: List Repo
        run: |
          pwd
          ls -al
      - name: Change File priviledge
        run: chmod +x ./script.sh
      - name: List Repo
        run: |
          pwd
          ls -al
      - name: Run a shell script
        uses: docker://node:12.14.1-alpine3.10
        with: 
          entrypoint: ./script.sh
          args: "Input Argument"
      - name: Send a Slack Message
        uses: docker://technosophos/slack-notify
        env: 
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: Hello From Slack!
---
name: Shell Commands
on: [pull_request]
jobs:
  run-shell-commands: 
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World!"
      - name: multiline script
        run: |
          node -v 
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-commands:
    runs-on: windows-latest
    needs: ['run-shell-commands']
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
---
name: Approve-Pull-Request
on: 
  pull_request:
    types: [closed]
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    id: label-added
    steps:
      - name: Label when approved
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"
          REMOVE_LABEL: "awaiting%20review"
  ManualApprovalStep:
    #name: PullRequestStatus
    runs-on: ubuntu-latest
    needs: label-added
    steps:
      - name: Check Labels
        if:  github.event.pull_request.merged && github.event.pull_request.labels == approved
        run: echo "Manual Approve passed"