  Approve-Pull-Request:
    on: 
      pull_request_review:
        branches:
          - master
    #name: Label approved pull requests
    jobs:
      labelWhenApproved:
        name: Label when approved
        runs-on: ubuntu-latest
        id: label-added
        steps:
        - name: Label when approved
          uses: pullreminders/label-when-approved-action@master
          env:
            APPROVALS: "1"
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ADD_LABEL: "approved"
            REMOVE_LABEL: "awaiting%20review"
      ManualApprovalStep:
        name: PullRequestStatus
        runs-on: ubuntu-latest
        needs: label-added
        steps:
          - name: Check Labels
            if: pull_request.action == closed && pull_request.merged == true 
            run: echo "Manual Approve passed"