  name: Approve-Pull-Request
  on: 
    pull_request:
      types: [closed]
      branches:
        - master
        - feature
  jobs:
    ManualApprovalStep:
      name: PullRequestStatus
      runs-on: ubuntu-latest
      #needs: label-added
      steps:
        - name: Check Labels
          if: pull_request.types == closed && pull_request.merged == true 
          run: echo "Manual Approve passed"