name: 'TestWF'
on:
  push:
    branches:
      - feature
jobs:
  Job1: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: eccho "Job1"
  Job2: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo "Job2"
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make changes to pull request
        run: date +%s > report.txt
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: example-patches
          delete-branch: true
          title: '[Example] Update report Pulling ${{ github.ref }} into master'
          body: |
            ":crown: *An automated PR*"   
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/nouranelanzeery1191/github_actions
          labels: |
            report
            automated pr
          assignees: "nouranelanzeery1191, nouran-elanzeery2"
          reviewers: nouranelanzeery1191
          team-reviewers: |
            owners
            maintainers
          milestone: "Milestone1"
          draft: false
      - name: Check output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
  Create_GitHub_Issue_onFailure:
      name: Create a GitHub Issue on Failure
      if: failure()
      runs-on: ubuntu-latest
      steps:
        - name: Create issue using REST API
          run: |
            curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/issues \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
              "title": "Automated issue for commit: ${{ github.sha }}",
              "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
              }'
  #CreateAPullRequest:
  #    name: Automatic Creation of Pull Request
  #    runs-on: ubuntu-latest
 #     steps:
 #       - name: Create Pull Request
 #         id: cpr
 #         uses: peter-evans/create-pull-request@v3
 #       - name: Check outputs
 #         run: |
 #           echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}" 
# - name: Confirm Changes
        #if: steps.changed-front.outputs.changed == 'true'
        ##run: echo "Diff command worked"