name: 'WF_Disp_input'
on:
  workflow_dispatch:
    inputs:
      git-ref: 
        description: Git Ref (Optional)    
        required: false
      environment:
        description: Environment to run this workflow on   
        required: true
        default: 'stage'
  push:
    branch:
      - feature
      - master
env:
  platform: nonlive
  path: workflows
jobs:
  createtest: 
    runs-on: ubuntu-latest
    # strategy: 
    #   matrix: 
    #     environment: ["nonlive"]    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Check For Changes
        uses: marceloprado/has-changed-path@v1
        id: changed-front
        with:
          paths: ./.github/$path
      - name: Print Env name
        if: steps.changed-front.outputs.changed == 'true' && env.platform == 'nonlive'
        run: |
            echo "The current environment is" ${platform}
            echo "The current environment is" ${env.platform}
  Livetest: 
    runs-on: ubuntu-latest    
    steps: 
      - name: Print Live Env.
        if: github.event.inputs.environment == 'stage'
        #steps.changed-front.outputs.changed == 'true' && ${{ github.event.inputs.var }} == live
        run: |
            echo "Hello World!"
            echo "The current environment is" ${{ github.event.inputs.environment }}