name: 'Infrastructure_Resources_Provisioning'
on:
  push:
    branches:
      - feature
      #- master
  pull_request:
    types: [closed]
    branches:
        - master
jobs:
  ProvisionSharedResources: 
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        environment: ["infra"]
        resources: ["vpc_setup"]     
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Check_For_Changes
        uses: marceloprado/has-changed-path@v1
        id: changed-front
        with:
          paths: ./github_actions/.github/workflows
      - name: Print Curent Branch name
        run: | 
          echo "This is running on branch ${GITHUB_REF##*/}"
      - name: Test if condition
        if: github.ref == 'master'
        run: |
          echo "if condition worked"
            echo "running on branch ${GITHUB_REF##*/}"
        
